# Generated by Django 5.2.16 on 2026-07-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "contract",
                    models.CharField(
                        choices=[
                            ("Month-to-month", "Month-to-month"),
                            ("One year", "One year"),
                            ("Two year", "Two year"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "internet_service",
                    models.CharField(
                        choices=[
                            ("DSL", "DSL"),
                            ("Fiber optic", "Fiber optic"),
                            ("No", "No"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tenure", models.PositiveIntegerField()),
                (
                    "monthly_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "churn_prediction",
                    models.CharField(
                        blank=True,
                        choices=[("Stay", "Stay"), ("Churn", "Churn")],
                        max_length=10,
                    ),
                ),
                ("churn_probability", models.FloatField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recommendation", models.TextField(blank=True)),
                ("last_predicted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_id", models.CharField(blank=True, max_length=30)),
                (
                    "prediction",
                    models.CharField(
                        choices=[("Stay", "Stay"), ("Churn", "Churn")], max_length=10
                    ),
                ),
                ("probability", models.FloatField()),
                ("risk_level", models.CharField(max_length=10)),
                ("recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
