# Generated by Django 5.2.16 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churnapp", "0002_predictionhistory_prediction_factors"),
    ]

    operations = [
        migrations.AddField(model_name="predictionhistory", name="age", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="predictionhistory", name="contract", field=models.CharField(blank=True, max_length=30)),
        migrations.AddField(model_name="predictionhistory", name="gender", field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="predictionhistory", name="internet_service", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="predictionhistory", name="monthly_charges", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="predictionhistory", name="tenure", field=models.PositiveIntegerField(blank=True, null=True)),
    ]
