# Generated by Django 5.2.16 on 2026-09-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("churnapp", "0003_predictionhistory_input_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(choices=[("Discount", "Offer discount"), ("Upgrade", "Upgrade plan"), ("Support", "Provide better support"), ("Contact", "Contact customer"), ("Other", "Other")], max_length=20)),
                ("status", models.CharField(choices=[("Planned", "Planned"), ("In Progress", "In Progress"), ("Completed", "Completed")], default="Planned", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prediction_history", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retention_actions", to="churnapp.predictionhistory")),
            ],
        ),
    ]
